//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coon.Compass.DtaGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal minimumAssumedPrecursorChargeState {
            get {
                return ((decimal)(this["minimumAssumedPrecursorChargeState"]));
            }
            set {
                this["minimumAssumedPrecursorChargeState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal maximumAssumedPrecursorChargeState {
            get {
                return ((decimal)(this["maximumAssumedPrecursorChargeState"]));
            }
            set {
                this["maximumAssumedPrecursorChargeState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableLockMassRecalibration {
            get {
                return ((bool)(this["enableLockMassRecalibration"]));
            }
            set {
                this["enableLockMassRecalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202.07770")]
        public decimal lockMassMZ {
            get {
                return ((decimal)(this["lockMassMZ"]));
            }
            set {
                this["lockMassMZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kenny {
            get {
                return ((bool)(this["kenny"]));
            }
            set {
                this["kenny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cleanPrecursor {
            get {
                return ((bool)(this["cleanPrecursor"]));
            }
            set {
                this["cleanPrecursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableEtdPreProcessing {
            get {
                return ((bool)(this["enableEtdPreProcessing"]));
            }
            set {
                this["enableEtdPreProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cleanTmtDuplex {
            get {
                return ((bool)(this["cleanTmtDuplex"]));
            }
            set {
                this["cleanTmtDuplex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cleanItraq4Plex {
            get {
                return ((bool)(this["cleanItraq4Plex"]));
            }
            set {
                this["cleanItraq4Plex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cleanTmt6Plex {
            get {
                return ((bool)(this["cleanTmt6Plex"]));
            }
            set {
                this["cleanTmt6Plex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cleanItraq8Plex {
            get {
                return ((bool)(this["cleanItraq8Plex"]));
            }
            set {
                this["cleanItraq8Plex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableDeIsotoping {
            get {
                return ((bool)(this["enableDeIsotoping"]));
            }
            set {
                this["enableDeIsotoping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string fragmentIntensityThreshold {
            get {
                return ((string)(this["fragmentIntensityThreshold"]));
            }
            set {
                this["fragmentIntensityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool groupByActivationEnergyTime {
            get {
                return ((bool)(this["groupByActivationEnergyTime"]));
            }
            set {
                this["groupByActivationEnergyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sequestDtaOutput {
            get {
                return ((bool)(this["sequestDtaOutput"]));
            }
            set {
                this["sequestDtaOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool omssaTxtOutput {
            get {
                return ((bool)(this["omssaTxtOutput"]));
            }
            set {
                this["omssaTxtOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mascotMgfOutput {
            get {
                return ((bool)(this["mascotMgfOutput"]));
            }
            set {
                this["mascotMgfOutput"] = value;
            }
        }
    }
}
